cci daemon: cci_daemon_impl Namespace Reference
cci_daemon_impl Namespace Reference
Classes
class cci_daemon_facade
class cci_daemon_kernel
core
class cci_daemon_plugin
class cci_shared_lib
shared library loading and access
class publish_and_subscribe_intf
class publish_and_subscribe_server
publish-subscribe related domain
Typedefs
using cci_daemon_facade_ptr = cci_daemon_facade *
using file_ptr = FILE *
using plugin_dictionary = std::map< std::string, cci_daemon_plugin >
using plugins_ptr = plugin_dictionary *
using size_ptr_t = size_t *
using cci_handle_t = void *
Enumerations
enum daemon_proc : unsigned long {
daemon_proc::dp_fork_background_proc = 0, daemon_proc::dp_fork_no_session_leader, daemon_proc::dp_make_session_leader, daemon_proc::dp_clear_file_create_mask,
daemon_proc::dp_change_to_root_dir, daemon_proc::dp_close_all_open_files, daemon_proc::dp_reopen_streams_dev_null, daemon_proc::dp_daemonized,
daemon_proc::dp_error
}
enum service_proc : unsigned long { service_proc::sp_default_service = 0, service_proc::sp_custom_dispatch }
Functions
std::ostream & operator<< (std::ostream &ostr, const cci_daemon_facade &df)
static void chromatic_terminate () noexcept
static void sighup_handler (int signal)
static void sigterm_handler (int signal)
static void sigsev_handler (int signal)
void print_stacktrace (FILE *out=stderr, unsigned max_frames=63)
void ** get_ebp (int dummy)
void print_walk_backtrace (FILE *out=stderr)
Variables
static volatile sig_atomic_t hup_received = 0
static const std::string
ldd_moniker ldd
static const std::string nm_moniker { "nm" }
Typedef Documentation
using cci_daemon_impl::cci_daemon_facade_ptr = typedef cci_daemon_facade*
Definition at line 39 of file cci_daemon.h.
using cci_daemon_impl::cci_handle_t = typedef void*
Definition at line 34 of file cci_shared_lib.h.
using cci_daemon_impl::file_ptr = typedef FILE*
Definition at line 40 of file cci_daemon.h.
using cci_daemon_impl::plugin_dictionary = typedef std::map<std::string , cci_daemon_plugin>
Definition at line 21 of file cci_daemon_kernel.h.
using cci_daemon_impl::plugins_ptr = typedef plugin_dictionary*
Definition at line 22 of file cci_daemon_kernel.h.
using cci_daemon_impl::size_ptr_t = typedef size_t*
Definition at line 18 of file cci_daemon_plugin.h.
Enumeration Type Documentation
enum cci_daemon_impl::daemon_proc : unsigned long strong
Enumerator
dp_fork_background_proc
dp_fork_no_session_leader
dp_make_session_leader
dp_clear_file_create_mask
dp_change_to_root_dir
dp_close_all_open_files
dp_reopen_streams_dev_null
dp_daemonized
dp_error
Definition at line 43 of file cci_daemon.h.
                                    : unsigned long
             {
                 dp_fork_background_proc = 0 ,
                 dp_fork_no_session_leader ,
                 dp_make_session_leader ,
                 dp_clear_file_create_mask ,
                 dp_change_to_root_dir ,
                 dp_close_all_open_files ,
                 dp_reopen_streams_dev_null ,
                 dp_daemonized ,
                 dp_error
             };
enum cci_daemon_impl::service_proc : unsigned long strong
Enumerator
sp_default_service
sp_custom_dispatch
Definition at line 56 of file cci_daemon.h.
                                     : unsigned long
             {
                 sp_default_service = 0 ,
                 sp_custom_dispatch
             };
Function Documentation
static void cci_daemon_impl::chromatic_terminate () static noexcept
Definition at line 173 of file cci_daemon.h.
Referenced by cci_daemon_impl::cci_daemon_facade::daemon_default_exec(), and main().
             {
                 //core dump if environment set , else use exit
                 char* s = getenv( "EF_DUMPCORE" );
                 if( s != nullptr && *s != '\0' )
                 {
                     abort();
                 }
                 else
                 {
                     exit( EXIT_FAILURE );
                 }
             }
void ** cci_daemon_impl::get_ebp (int dummy)
Definition at line 93 of file cci_stack_trace.cpp.
Referenced by print_walk_backtrace().
 {
     void** ebp = (void** )&dummy - 2;
     return( ebp );
 }
std::ostream& cci_daemon_impl::operator<< (std::ostream & ostr, const cci_daemon_facade & df) inline
Definition at line 164 of file cci_daemon.h.
             {
                 //todo
                 return ostr << "daemon facade "
                             << "log=>" << cci_daemon_impl::cci_daemon_facade::log_path;
             }
void cci_daemon_impl::print_stacktrace (FILE * out = stderr, unsigned max_frames = 63)
Definition at line 10 of file cci_stack_trace.cpp.
Referenced by cci_daemon_impl::cci_daemon_facade::_bt().
 {
         fprintf(out, "stack trace:\n");
         // storage array for stack trace address data
         void* addrlist[max_frames+1];
         // retrieve current stack addresses
         int addrlen = backtrace(addrlist, sizeof(addrlist) / sizeof(void*));
         if (addrlen == 0) {
         fprintf(out, "  <empty, possibly corrupt>\n");
         return;
         }
         // resolve addresses into strings containing "filename(function+address)",
         // this array must be free()-ed
         char** symbollist = backtrace_symbols(addrlist, addrlen);
         // allocate string which will be filled with the demangled function name
         size_t funcnamesize = 256;
         char* funcname = (char*)malloc(funcnamesize);
         // iterate over the returned symbol lines. skip the first, it is the
         // address of this function.
         for (int i = 1; i < addrlen; i++)
         {
             char *begin_name = 0, *begin_offset = 0, *end_offset = 0;
             // find parentheses and +address offset surrounding the mangled name:
             // ./module(function+0x15c) [0x8048a6d]
             for (char *p = symbollist[i]; *p; ++p)
             {
                 if (*p == '(')
                 begin_name = p;
                 else if (*p == '+')
                 begin_offset = p;
                 else if (*p == ')' && begin_offset) {
                 end_offset = p;
                 break;
                 }
             }
             if (begin_name && begin_offset && end_offset
                 && begin_name < begin_offset)
             {
                 *begin_name++ = '\0';
                 *begin_offset++ = '\0';
                 *end_offset = '\0';
                 // mangled name is now in [begin_name, begin_offset) and caller
                 // offset in [begin_offset, end_offset). now apply
                 // __cxa_demangle():
                 int status;
                 char* ret = abi::__cxa_demangle(begin_name,
                                 funcname, &funcnamesize, &status);
                 if (status == 0) {
                 funcname = ret; // use possibly realloc()-ed string
                 fprintf(out, "  %s : %s+%s\n",
                     symbollist[i], funcname, begin_offset);
                 }
                 else {
                 // demangling failed. Output function name as a C function with
                 // no arguments.
                 fprintf(out, "  %s : %s()+%s\n",
                     symbollist[i], begin_name, begin_offset);
                 }
             }
             else
             {
                 // couldn't parse the line? print the whole line.
                 fprintf(out, "  %s\n", symbollist[i]);
             }
         }
         free(funcname);
         free(symbollist);
 }
void cci_daemon_impl::print_walk_backtrace (FILE * out = stderr)
Definition at line 102 of file cci_stack_trace.cpp.
Referenced by cci_daemon_impl::cci_daemon_facade::_btw().
 {
         int dummy  = 0;
         int frame = 0;
         Dl_info dlip;
         void** ebp = get_ebp( dummy );
         void** ret = NULL;
         //instruction pointer
         fprintf( out , "stack backtrace walk: \n" );
         while( *ebp )
         {
             ret = ebp + 1;
             dladdr( *ret, &dlip );
             fprintf(  out ,
                      "frame %d: [ebp=0x%08x] [ret=0x%08x] %s\n" ,
                      frame++ ,
                      *ebp ,
                      *ret ,
                      dlip.dli_sname );
             //next frame pointer
             ebp = (void**)(*ebp);
         }
 }
static void cci_daemon_impl::sighup_handler (int signal) static
Definition at line 187 of file cci_daemon.h.
Referenced by cci_daemon_impl::cci_daemon_facade::daemon_default_exec().
             {
                 hup_received = 1;
             }
static void cci_daemon_impl::sigsev_handler (int signal) static
Definition at line 200 of file cci_daemon.h.
             {
                void *array[10];
                size_t size;
                file_ptr log_p { nullptr };
                int fn( 0L );
               // void*'s for all entries on the stack
               size = backtrace( array, 10 );
               // print out all the frames to stderr
               if( log_p )
               {
                   fprintf( log_p , "error: signal %d:\n" , signal );
                   backtrace_symbols_fd( array, size, fn );
                   exit( 1 );
               }
             }
static void cci_daemon_impl::sigterm_handler (int signal) static
Definition at line 191 of file cci_daemon.h.
Referenced by cci_daemon_impl::cci_daemon_facade::daemon_default_exec().
             {
                 openlog( "cci-daemon" , 0  , LOG_USER );
                 syslog ( LOG_USER | LOG_INFO , "%s", "cci-daemon deactivated by sigterm...." );
                 closelog();
                 exit( EXIT_SUCCESS );
             }
Variable Documentation
volatile sig_atomic_t cci_daemon_impl::hup_received = 0 static
Definition at line 186 of file cci_daemon.h.
Referenced by cci_daemon_impl::cci_daemon_facade::daemon_default_exec(), and sighup_handler().
const std::string ldd_moniker cci_daemon_impl::ldd static
Definition at line 29 of file cci_shared_lib.h.
const std::string cci_daemon_impl::nm_moniker { "nm" } static
Definition at line 30 of file cci_shared_lib.h.