cci daemon: proc_ace::proc_handler Class Reference
proc_ace::proc_handler Class Reference
#include <proc_ace_acceptor.h>
Public Types
typedef ACE_Svc_Handler
< ACE_SOCK_STREAM,
ACE_NULL_SYNCH > inherited
typedef int(proc_handler::* ptr_to_function)(const std::string &strParams)
typedef std::map< std::string,
ptr_to_function > map_of_commands
Public Member Functions
proc_handler (const ACE_Time_Value &max_inactivity=ACE_Time_Value(max_client_timeout))
void destroy ()
int open (void *accept)
int close (u_long flags=0)
virtual int handle_close (ACE_HANDLE handle=ACE_INVALID_HANDLE, ACE_Reactor_Mask mask=ACE_Event_Handler::ALL_EVENTS_MASK)
int handle_timeout (const ACE_Time_Value &now, const void *act)
proc_acceptor * acceptor ()
std::string computer_name () const noexcept
std::ostringstream & stream ()
std::string token () const noexcept
map_of_commands & command_map ()
bool silent ()
proc_command command () const noexcept
proc_packet_error error_packet () const noexcept
std::string command_str () const noexcept
void silent (bool bSilent)
void error_packet (proc_packet_error error)
void acceptor (proc_acceptor_ptr acceptor)
void command (proc_command command)
void command_str (const std::string &str_command)
void token (const std::string &str_token)
int on_login (const std::string &params)
Static Public Member Functions
static std::string ucase (const std::string &str)
static std::string lcase (const std::string &str)
static void gnaw (std::string &str, const std::string &token)
static void rtrimlast (std::string &str, const std::string &token)
static void chomp (std::string &str, const std::string &token)
static std::string ltrim (const std::string &szToTrim, const std::string &szTrimChars)
static std::string rtrim (const std::string &szToTrim, const std::string &szTrimChars)
static std::string extract_quoted_string (const std::string &str)
Protected Member Functions
proc_thread_pool * thread_pool ()
concurrency_t concurrency ()
int svc ()
int handle_input (ACE_HANDLE handle)
int process (char *rdbuf, int rdbuf_len)
~proc_handler ()
void output_boiler_plate (std::string str_concurrency="")
std::string output_prompt (bool bToken=true)
void map_commands ()
void perform (const std::string &str)
void flush_stream_to_connector ()
void flush_binary_stream_to_connector (unsigned char *u_buffer, unsigned long dwLen)
void format_packet_error (proc_packet_error pe)
std::string client_addr ()
void stream_out (const std::string &str)
void stream_out (const std::string &str, unsigned long len)
void stream_out (const byte_ptr &ptrBytes, unsigned long len)
void output_ok_response (const std::string &ack)
void output_no_response (const std::string &nack)
void flush_immediate (const std::string &atom)
void parse_command (const std::string &packet, map_of_parts &parts, unsigned short &usCommandParamCount)
bool check_connection_state (proc_state state)
void update_connection_state (proc_set_op op, proc_state state)
Protected Attributes
ACE_thread_t creator_
Detailed Description
Definition at line 236 of file proc_ace_acceptor.h.
Member Typedef Documentation
typedef ACE_Svc_Handler<ACE_SOCK_STREAM, ACE_NULL_SYNCH> proc_ace::proc_handler::inherited
Definition at line 242 of file proc_ace_acceptor.h.
typedef std::map<std::string , ptr_to_function> proc_ace::proc_handler::map_of_commands
Definition at line 245 of file proc_ace_acceptor.h.
typedef int(proc_handler::* proc_ace::proc_handler::ptr_to_function)(const std::string &strParams)
Definition at line 244 of file proc_ace_acceptor.h.
Constructor & Destructor Documentation
proc_handler::proc_handler (const ACE_Time_Value & max_inactivity = ACE_Time_Value (max_client_timeout))
Definition at line 38 of file proc_ace_handler.cpp.
                                                                   :   m_proc_acceptor{ nullptr } ,
                                                                         m_current_command{ proc_command::proc_no_command } ,
                                                                         m_proc_packet_error{ proc_packet_error::peNoPacketError } ,
                                                                         m_dwTimerToken{ 0 } ,
                                                                         m_maximumTimeToWait{ max_inactivity } ,
                                                                         m_bSilent{ false } ,
                                                                         creator_ { ACE_Thread::self() }
 {
               ACE_Trace _( ACE_TEXT( "proc_handler::proc_handler" ) , __LINE__ );
               try
               {
                   char hostname[1024];
                   gethostname( hostname , 1023 );
                   m_strComputerName = hostname;
                   m_currentState.insert( proc_state::oesNonAuthenticated );
               }
               catch( ... )
               {
                  //
               }
               m_set_map.insert( make_pair( proc_set_param::ospPrompt , true ) );
 }
proc_handler::~proc_handler () protected
Definition at line 66 of file proc_ace_handler.cpp.
 {
             ACE_Trace _( ACE_TEXT( "proc_handler::~proc_handler" ) , __LINE__ );
             peer().close();
 }
Member Function Documentation
proc_acceptor* proc_ace::proc_handler::acceptor () inline
Definition at line 326 of file proc_ace_acceptor.h.
Referenced by concurrency(), open(), and thread_pool().
 { return ( m_proc_acceptor ); }
void proc_ace::proc_handler::acceptor (proc_acceptor_ptr acceptor) inline
Definition at line 339 of file proc_ace_acceptor.h.
Referenced by acceptor().
 { m_proc_acceptor = acceptor; }
bool proc_handler::check_connection_state (proc_state state) protected
Definition at line 688 of file proc_ace_handler.cpp.
Referenced by on_login().
 {
             bool bRet = false;
             current_state::iterator iter = m_currentState.find( state );
             iter == m_currentState.end() ? bRet = false  : bRet = true;
             return ( bRet );
 }
void proc_handler::chomp (std::string & str, const std::string & token) static
Definition at line 724 of file proc_ace_handler.cpp.
Referenced by parse_command().
 {
             string strTemp( str );
             if( str.empty() )
             {
                 return;
             }
             string::size_type idx = str.find( token );
             if( idx != string::npos )
             {
                 str = str.substr( 0 , --idx );
             }
 }
string proc_handler::client_addr () protected
Definition at line 190 of file proc_ace_handler.cpp.
Referenced by handle_close(), and handle_timeout().
 {
             ACE_INET_Addr addr;
             char addrstr[MAXHOSTNAMELEN + 1];
             peer().get_remote_addr( addr );
             addr.addr_to_string( addrstr , sizeof( addrstr ) );
             string strTemp( addrstr );
             return ( strTemp );
 }
int proc_handler::close (u_long flags = 0)
Definition at line 255 of file proc_ace_handler.cpp.
 {
               ACE_Trace _( ACE_TEXT( "proc_handler::closed" ) , __LINE__ );
               ACE_UNUSED_ARG( flags );
               destroy ();
               return ( 0L );
 }
proc_command proc_ace::proc_handler::command () const inline noexcept
Definition at line 332 of file proc_ace_acceptor.h.
Referenced by format_packet_error(), on_login(), perform(), and process().
 { return ( m_current_command ); }
void proc_ace::proc_handler::command (proc_command command) inline
Definition at line 340 of file proc_ace_acceptor.h.
Referenced by command().
 { m_current_command = command; }
map_of_commands& proc_ace::proc_handler::command_map () inline
Definition at line 330 of file proc_ace_acceptor.h.
Referenced by map_commands(), and perform().
 { return ( m_command_map ); }
std::string proc_ace::proc_handler::command_str () const inline noexcept
Definition at line 334 of file proc_ace_acceptor.h.
Referenced by output_no_response(), and parse_command().
 { return ( ucase( m_strCommand ) ); }
void proc_ace::proc_handler::command_str (const std::string & str_command) inline
Definition at line 341 of file proc_ace_acceptor.h.
 { m_strCommand = str_command; }
std::string proc_ace::proc_handler::computer_name () const inline noexcept
Definition at line 327 of file proc_ace_acceptor.h.
Referenced by output_boiler_plate().
 { return ( m_strComputerName ); }
concurrency_t proc_handler::concurrency () protected
Definition at line 74 of file proc_ace_handler.cpp.
Referenced by handle_input(), and open().
 {           return ( acceptor()->concurrency () );}
void proc_handler::destroy ()
Definition at line 82 of file proc_ace_handler.cpp.
Referenced by close(), handle_close(), and handle_timeout().
 {
            ACE_Trace _( ACE_TEXT( "proc_handler::destroy" ) , __LINE__ );
            reactor()->remove_handler ( this, REMOVE_MASK );
            delete this;
 }
proc_packet_error proc_ace::proc_handler::error_packet () const inline noexcept
Definition at line 333 of file proc_ace_acceptor.h.
Referenced by on_login(), parse_command(), perform(), and process().
 { return ( m_proc_packet_error ); }
void proc_ace::proc_handler::error_packet (proc_packet_error error) inline
Definition at line 338 of file proc_ace_acceptor.h.
 { m_proc_packet_error = error; }
string proc_handler::extract_quoted_string (const std::string & str) static
Definition at line 863 of file proc_ace_handler.cpp.
 {
            string s( str );
            if( s.empty() )
            {
                return ( s );
            }
            string::size_type idx = s.find_first_of( "\"" );
            if( idx != string::npos )
            {
                 s.erase( idx , 1 );
                 idx = s.find_last_of( "\"" );
                 if( idx != string::npos )
                 {
                     s.erase( idx , 1 );
                 }
            }
            return ( s );
 }
void proc_handler::flush_binary_stream_to_connector (unsigned char * u_buffer, unsigned long dwLen) protected
Definition at line 175 of file proc_ace_handler.cpp.
 {
             if( silent() == true )
             {
                 stream().str( "" );
                 return;
             }
             ACE_Time_Value timeout( 5 );
             peer().send( (unsigned char*) u_buffer , dwLen , &timeout );
 }
void proc_handler::flush_immediate (const std::string & atom) protected
Definition at line 586 of file proc_ace_handler.cpp.
 {
             stream() << atom;
             flush_stream_to_connector();
 }
void proc_handler::flush_stream_to_connector () protected
Definition at line 155 of file proc_ace_handler.cpp.
Referenced by flush_immediate(), format_packet_error(), handle_close(), handle_timeout(), output_boiler_plate(), perform(), and process().
 {
             ACE_Trace _( ACE_TEXT( "proc_handler::flush_stream_to_connector" ) , __LINE__ );
             if( silent() == true )
             {
                 stream().str( "" );
                 return;
             }
             ACE_Time_Value timeout( 2 );
             size_t bytes_sent;
             string strOutput ( stream().str() );
             peer().send_n( (char*) strOutput.c_str() , strOutput.size() , &timeout , &bytes_sent );
             stream().str( "" );
 }
void proc_handler::format_packet_error (proc_packet_error pe) protected
Definition at line 529 of file proc_ace_handler.cpp.
Referenced by process().
 {
             command( proc_command::proc_error );
             stream() << output_prompt();
             stream() << " NO ";
             if( pe == proc_packet_error::peNoToken ) stream() << "no token supplied - expected";
             else if( pe == proc_packet_error::peTokenTooLong) stream() << "token too long";
             else if( pe == proc_packet_error::peNoCommand ) stream() << "no command supplied - expected";
             else if( pe == proc_packet_error::peCommandTooLong ) stream() << "buffer to large";
             else if( pe == proc_packet_error::peTooManyParameters ) stream() << "too many parameters supplied";
             else if( pe == proc_packet_error::peInvalidPayload ) stream() << "invalid buffer";
             else if( pe == proc_packet_error::peInvalidSyntax ) stream() << "invalid syntax";
             else if( pe == proc_packet_error::peUnrecognizedCommand ) stream() << "command unrecognized";
             else if( pe == proc_packet_error::peSelectState ) stream() << " a target must be selected before a query";
             else if( pe == proc_packet_error::peTooFewParameters ) stream() << " too few parameters - more";
             else if( pe == proc_packet_error::peNoParametersExpectedGotSome ) stream() << " no parameters expected - got some";
             else if( pe == proc_packet_error::peParametersExpectedGotNone ) stream() << "parameters expected - got none";
             else if( pe == proc_packet_error::peFailure ) stream() << "a server operation within this context failed";
             else if( pe == proc_packet_error::peInvalidObject ) stream() << "object does not exist";
             else if( pe == proc_packet_error::peInvalidSpecification ) stream() << "invalid specification";
             else if( pe == proc_packet_error::peNoSpecification ) stream() << "no specification";
             else if( pe == proc_packet_error::peInvalidState ) stream() << "invalid state";
             else if( pe == proc_packet_error::peAttributeNotSupported ) stream() << "attribute not supported";
             else if( pe == proc_packet_error::peNotAuthenticated ) stream() << "please login";
             else if( pe == proc_packet_error::peAlreadyAuthenticated ) stream() << "already logged in";
             else if( pe == proc_packet_error::peNotEnoughPrivileges ) stream() << "not enough privileges";
             stream() << crlf;
             stream() << output_prompt( false );
             flush_stream_to_connector();
 }
void proc_handler::gnaw (std::string & str, const std::string & token) static
Definition at line 742 of file proc_ace_handler.cpp.
 {
             string::size_type st;
             st = str.find( token , 0 );
             if( st != string::npos )
             {
                 str.resize( st );
             }
 }
int proc_handler::handle_close (ACE_HANDLE handle = ACE_INVALID_HANDLE, ACE_Reactor_Mask mask = ACE_Event_Handler::ALL_EVENTS_MASK) virtual
Definition at line 301 of file proc_ace_handler.cpp.
 {
               ACE_Trace _( ACE_TEXT( "proc_handler::handle_close" ) , __LINE__ );
               ACE_UNUSED_ARG (handle);
               ACE_UNUSED_ARG (mask);
               stream() << " * goodbye "
                        << client_addr()
                        << "......chromatic unvierse cci-daemon-dispatcher" << crlf;
               flush_stream_to_connector();
               this->destroy ();
               return 0;
 }
int proc_handler::handle_input (ACE_HANDLE handle) protected
Definition at line 267 of file proc_ace_handler.cpp.
 {
               ACE_Trace _( ACE_TEXT( "proc_handler::handle_input" ) , __LINE__ );
               ACE_UNUSED_ARG ( handle );
               m_lastActivityTime = reactor()->timer_queue()->gettimeofday();
               if ( concurrency () ==  concurrency_t::thread_pool_ )
               {
                  if ( ACE_OS::thr_equal (ACE_Thread::self(),
                                          creator_) )
                 {
                       reactor ()->remove_handler ( this, REMOVE_MASK );
                       return ( thread_pool ()->enqueue ( this ) );
                 }
               }
               char buf[cmd_buffer_len];
               int rval = process ( buf, sizeof (buf) );
               if ( concurrency () ==  concurrency_t::thread_pool_ )
               {
                   if ( rval != -1 )
                   {
                     reactor ()->register_handler ( this,
                                                    REGISTER_MASK );
                   }
               }
               return rval;
 }
int proc_handler::handle_timeout (const ACE_Time_Value & now, const void * act)
Definition at line 319 of file proc_ace_handler.cpp.
 {
                 ACE_Trace _( ACE_TEXT( "proc_handler::handle_timeout" ) , __LINE__ );
                 short unsigned int* sui = (short unsigned int*) act;
                 if( *sui == (short unsigned int) timer_id )
                 {
                     if( ( now - m_lastActivityTime ) >= m_maximumTimeToWait )
                     {
                         cout << client_addr() << " timed out" << endl;
                         stream() <<  " autologout; idle for too long" << crlf;
                         flush_stream_to_connector();
                         reactor()->remove_handler( this , ACE_Event_Handler::READ_MASK );
                         this->destroy ();
                     }
                 }
                 return ( 0 );
 }
string proc_handler::lcase (const std::string & str) static
Definition at line 822 of file proc_ace_handler.cpp.
Referenced by perform().
 {
             string localstr( str );
             if( localstr.empty() )
             {
                 return( "" );
             }
             string::iterator iter = localstr.begin();
             while ( iter != localstr.end() )
             {
                 *iter = tolower( *iter );
                 iter++;
             }
             return ( localstr );
 }
string proc_handler::ltrim (const std::string & szToTrim, const std::string & szTrimChars) static
Definition at line 777 of file proc_ace_handler.cpp.
 {
             string szToReturn = szToTrim;
             while( strchr( szTrimChars.c_str(), szToReturn[0] ) != NULL )
             {
                 if( szToReturn.length() < 1 )
                 {
                     return ( "" );
                 }
                 szToReturn.replace( 0, 1, "" );
             }
             return szToReturn;
 }
void proc_handler::map_commands () protected
Definition at line 124 of file proc_ace_handler.cpp.
Referenced by open().
 {
             command_map().insert( std::pair<string , ptr_to_function> ( "login", &proc_handler::on_login ) );
             /*command_map().insert( std::pair<string , ptrToFunction> ( "logout", &chromatic_handler::on_logout ) );
             command_map().insert( std::pair<string , ptrToFunction> ( "create", &chromatic_handler::on_create ) );
             command_map().insert( std::pair<string , ptrToFunction> ( "select", &chromatic_handler::on_select ) );
             command_map().insert( std::pair<string , ptrToFunction> ( "examine", &chromatic_handler::on_examine ) );
             command_map().insert( std::pair<string , ptrToFunction> ( "list", &chromatic_handler::on_list ) );
             command_map().insert( std::pair<string , ptrToFunction> ( "delete", &chromatic_handler::on_delete ) );
             command_map().insert( std::pair<string , ptrToFunction> ( "rename", &chromatic_handler::on_rename ) );
             command_map().insert( std::pair<string , ptrToFunction> ( "lsub", &chromatic_handler::on_lsub ) );
             command_map().insert( std::pair<string , ptrToFunction> ( "subscribe", &chromatic_handler::on_subscribe ) );
             command_map().insert( std::pair<string , ptrToFunction> ( "unsubscribe", &chromatic_handler::on_unsubscribe ) );
             command_map().insert( std::pair<string , ptrToFunction> ( "noop", &chromatic_handler::on_noop ) );
             command_map().insert( std::pair<string , ptrToFunction> ( "check", &chromatic_handler::on_check ) );
             command_map().insert( std::pair<string , ptrToFunction> ( "capability", &chromatic_handler::on_capability ) );
             command_map().insert( std::pair<string , ptrToFunction> ( "search", &chromatic_handler::on_search ) );
             command_map().insert( std::pair<string , ptrToFunction> ( "copy", &chromatic_handler::on_copy ) );
             command_map().insert( std::pair<string , ptrToFunction> ( "fetch", &chromatic_handler::on_fetch ) );
             command_map().insert( std::pair<string , ptrToFunction> ( "store", &chromatic_handler::on_store ) );
             command_map().insert( std::pair<string , ptrToFunction> ( "uid", &chromatic_handler::on_uid ) );
             command_map().insert( std::pair<string , ptrToFunction> ( "close", &chromatic_handler::on_close ) );
             command_map().insert( std::pair<string , ptrToFunction> ( "expunge", &chromatic_handler::on_expunge ) );
             command_map().insert( std::pair<string , ptrToFunction> ( "append", &chromatic_handler::on_append ) );
             command_map().insert( std::pair<string , ptrToFunction> ( "starttls", &chromatic_handler::on_starttls ) );
             command_map().insert( std::pair<string , ptrToFunction> ( "status", &chromatic_handler::on_status ) );*/
 }
int proc_handler::on_login (const std::string & params)
Definition at line 891 of file proc_ace_handler.cpp.
Referenced by map_commands().
 {
         ACE_Trace _( ACE_TEXT( "chromatic_handler::on_login" ) , __LINE__ );
         command( proc_command::proc_login );
         if( check_connection_state( proc_state::oesAuthenticated ) == true )
         {
             error_packet( proc_packet_error::peAlreadyAuthenticated );
             return ( 0 );
         }
         ostringstream ostr;
         //todo
         bool bRet = true;// context_ptr()->on_login( params , ostr.str() , stream() );
         if( bRet == true )
         {
             update_connection_state( proc_set_op::osopAdd , proc_state::oesAuthenticated );
             output_ok_response( "login completed" );
         }
         else
         {
             output_no_response( "login failed" );
         }
     return ( 0 );
 }
int proc_handler::open (void * accept)
Definition at line 205 of file proc_ace_handler.cpp.
 {
               ACE_Trace _( ACE_TEXT( "proc_handler::open" ) , __LINE__ );
               output_boiler_plate();
               map_commands();
               silent( false );
               acceptor ( ( proc_acceptor_ptr) accept);
               string strConcurrency;
               //check for timeout every 30 seconds
               ACE_Time_Value reschedule( m_maximumTimeToWait.sec() / 60 );
               m_dwTimerToken = reactor()->schedule_timer( this ,
                                                           (void*) timer_id ,
                                                           m_maximumTimeToWait ,
                                                           reschedule );
               if ( concurrency () == concurrency_t::thread_per_connection_ )
               {
                 return activate ( THR_DETACHED );
               }
               reactor ( acceptor()->reactor () );
               ACE_INET_Addr addr;
               if ( peer ().get_remote_addr (addr) == -1 ) { return ( -1 ); }
               if ( reactor ()->register_handler ( this,
                                                   REGISTER_MASK ) == -1 )
               {
                 ACE_ERROR_RETURN ((LM_ERROR,
                                    "(%P|%t) can't register with reactor\n"),
                                   -1);
               }
               ACE_DEBUG ((LM_DEBUG,
                           "(%P|%t) connected with %s\n",
                           addr.get_host_name () ) );
               return ( 0L );
 }
void proc_handler::output_boiler_plate (std::string str_concurrency = "") protected
Definition at line 93 of file proc_ace_handler.cpp.
Referenced by open().
 {
               stream() << "* OK cci-dispatch daemon speaking.... "
                        << computer_name()
                        << " chromatic universe 2017 all rights reserved  ready";
               stream() << crlf;
               stream() << output_prompt( false );
               flush_stream_to_connector();
 }
void proc_handler::output_no_response (const std::string & nack) protected
Definition at line 717 of file proc_ace_handler.cpp.
Referenced by on_login().
 {
             stream() << token() << " " << "NO " << nack << crlf;
             command_str( "" );
 }
void proc_handler::output_ok_response (const std::string & ack) protected
Definition at line 682 of file proc_ace_handler.cpp.
Referenced by on_login().
 {
             stream() << token() << " " << "OK " << ack << crlf;
 }
string proc_handler::output_prompt (bool bToken = true) protected
Definition at line 108 of file proc_ace_handler.cpp.
Referenced by format_packet_error(), output_boiler_plate(), perform(), and process().
 {
               ostringstream ostr;
               if( btoken == true )
               {
                     ostr << token() ;
                     ostr << ends;
               }
               return ( ostr.str() );
 }
void proc_handler::parse_command (const std::string & packet, map_of_parts & parts, unsigned short & usCommandParamCount) protected
Definition at line 596 of file proc_ace_handler.cpp.
Referenced by perform().
 {
             if( packet.empty() )
             {
                 error_packet( proc_packet_error::peInvalidSyntax );
                 return;
             }
             string space( " " );
             string str( packet );
             ACE_DEBUG ((LM_DEBUG,
                           "\n\t------------------------Client Packet------------------------\n" ) );
             ACE_DEBUG ((LM_DEBUG,
                           "(%P|%t) %s %s\n" , (char*) token().c_str() , (char*) str.c_str() ) );
             //get the token
             string::size_type idx = str.find_first_of( space );
             if( idx != string::npos )
             {
                 string strtoken;
                 strtoken = str.substr( 0 , idx );
                 if( strtoken.size() > constMaxTokenLength )
                 {
                     error_packet( proc_packet_error::peTokenTooLong );
                     return;
                 }
                 parts.insert( make_pair( proc_packet_part::ppToken , strtoken ) );
                 token( strtoken );
                 //truncate
                 idx++;
                 str = str.substr( idx );
                 if( str.size() == 0 )
                 {
                     error_packet( proc_packet_error::peInvalidSyntax );
                     return;
                 }
                 //get the command
                 string strcommand;
                 idx = str.find_first_of( space );
                 if( idx == string::npos )
                 {
                     //no params
                     uscommandParamCount = 0;
                     strcommand = str;
                     rtrimlast( strcommand , "\n" );
                     command_str( strcommand );
                     parts.insert( make_pair( proc_packet_part::ppCommand , strcommand ) );
                 }
                 else
                 {
                     strcommand = str.substr( 0 , idx );
                     command_str( strcommand );
                     //truncate
                     idx++;
                     str = str.substr( idx );
                     parts.insert( make_pair( proc_packet_part::ppCommand , strcommand ) );
                     chomp( str , "\n" );
                     parts.insert( make_pair( proc_packet_part::ppPayload , str ) );
                 }
             }
             else
             {
                 error_packet( proc_packet_error::peNoCommand );
                 return;
             }
             error_packet( proc_packet_error::peNoPacketError );
 }
void proc_handler::perform (const std::string & str) protected
Definition at line 462 of file proc_ace_handler.cpp.
Referenced by process().
 {
             if( str.empty() )
             {
                 error_packet( proc_packet_error::peInvalidPayload );
                 return;
             }
             unsigned short uscommands = 0;
             map_of_parts PartsMap;
             //parse the packet
             parse_command( str , PartsMap , uscommands );
             if( error_packet() != proc_packet_error::peNoPacketError )
             {
                 return;
             }
             //call the required function
             map_of_parts::iterator pIter = PartsMap.find( proc_packet_part::ppCommand );
             if( pIter != PartsMap.end() )
             {
                 string strcommand( pIter->second );
                 strcommand = lcase( strcommand );
                 map_of_commands::iterator c_iter = command_map().find( strcommand );
                 if( c_iter  == command_map().end() )
                 {
                     error_packet( proc_packet_error::peUnrecognizedCommand );
                     return;
                 }
                 proc_handler::ptr_to_function ptr_func = c_iter->second;
                 if( ptr_func == NULL )
                 {
                     stream() << output_prompt( false );
                     stream() << "NO no default action for this keyword" << crlf;
                     flush_stream_to_connector();
                     return;
                 }
                 //params
                 pIter = PartsMap.find( proc_packet_part::ppPayload );
                 string strPayload;
                 pIter != PartsMap.end() ? strPayload = pIter->second : strPayload = "";
                 int lRetVal = ( this->*ptr_func ) ( strPayload );
                 if( ( lRetVal != 0 ) || ( command() == proc_command::proc_error ) )
                 {
                     return;
                 }
             }
             else
             {
                 return;
             }
             return;
 }
int proc_handler::process (char * rdbuf, int rdbuf_len) protected
Definition at line 364 of file proc_ace_handler.cpp.
Referenced by handle_input(), and svc().
 {
               //process request
               ssize_t bytes_read;
               const  char ctrl_c = 3;
               const  char ctrl_z = 26;
               //memory stream - the stream buffer could be very large , put it on the heap
               auto ostr = std::make_unique<std::ostringstream>() ;
               //we'll only wait this
               ACE_Time_Value timeout( 50 );
               memset( (void*) rdbuf , '\0' , rdbuf_len );
               error_packet( proc_packet_error::peNoPacketError );
               //read buffer
               while ( ( bytes_read = peer().recv ( rdbuf, rdbuf_len , &timeout) ) > 0 )
               {
                    *ostr << rdbuf;
                    //zero read buufer
                    memset( (void*) rdbuf , '\0' , sizeof( rdbuf_len ) );
                    string::size_type st = ostr->str().find( ctrl_c );
                    string::size_type dt = ostr->str().find( ctrl_z );
                    //ctrl-c,ctrl-z
                    //trap for console termination
                    if( ( st != string::npos ) || ( dt != string::npos) )
                    {
                        return ( -1 );
                    }
                    //request terminator
                    st = ostr->str().find( "\n" );
                    if( st == string::npos )
                    {
                        if( ostr->str().size() <= constCommandBufferLength )
{
                             continue;
                        }
                    }
                    if( bytes_read > 0 )
                    {
                        //execute
                        perform( ostr->str() );
                        ACE_DEBUG ((LM_DEBUG, "\n\t\t------------------------------\n",
                                    (char*) ostr->str().c_str() ) );
                        //just a line feed or waiting - ignore
                        if( ( ostr->str().find ( "\n" ) != string::npos ) && ( ostr->str().size() == 2L ) )
{
                             stream() << output_prompt( false );
                             flush_stream_to_connector();
                             break;
                        }
                        //logout
                        if( command() != proc_command::proc_logout )
{
                             //fini
                             if( error_packet() != proc_packet_error::peNoPacketError )
{
                                 format_packet_error( error_packet() );
                                 break;
                             }
                         }
                         else
{
                             //snafu
                             flush_stream_to_connector();
                             return ( -1 );
                         }
                         flush_stream_to_connector();
                         ostr->str( "" );
                         break;
                    }
             }
             //set buffer to empty
             ostr->str( "" );
             ostr.release();
             return ( 0L );
 }
string proc_handler::rtrim (const std::string & szToTrim, const std::string & szTrimChars) static
Definition at line 795 of file proc_ace_handler.cpp.
 {
             string szToReturn = szToTrim;
             int nLastPos = szToReturn.length() - 1;
             if( nLastPos <= 0 )
             {
                 return ( "" );
             }
             while( strchr( szTrimChars.c_str(), szToReturn[nLastPos] ) != NULL )
             {
                 szToReturn.replace( nLastPos, 1, "" );
                 nLastPos = szToReturn.length() - 1;
                 if( nLastPos <= 0 )
                 {
                     return ( "" );
                 }
             }
             return szToReturn;
 }
void proc_handler::rtrimlast (std::string & str, const std::string & token) static
Definition at line 755 of file proc_ace_handler.cpp.
Referenced by parse_command().
 {
             if ( str.empty() )
             {
                 return;
             }
             string::size_type idx = str.find_last_of( (char*) token.c_str() );
             //if not the last ignore
             if( idx != str.size() - 1 )
             {
                 return;
             }
             if( idx != string::npos )
             {
                 str = str.substr( 0 , --idx );
             }
 }
bool proc_ace::proc_handler::silent () inline
Definition at line 331 of file proc_ace_acceptor.h.
Referenced by flush_binary_stream_to_connector(), flush_stream_to_connector(), and open().
 { return ( m_bSilent ); }
void proc_ace::proc_handler::silent (bool bSilent) inline
Definition at line 337 of file proc_ace_acceptor.h.
 { m_bSilent = bSilent; }
std::ostringstream& proc_ace::proc_handler::stream () inline
Definition at line 328 of file proc_ace_acceptor.h.
Referenced by flush_binary_stream_to_connector(), flush_immediate(), flush_stream_to_connector(), format_packet_error(), handle_close(), handle_timeout(), output_boiler_plate(), output_no_response(), output_ok_response(), perform(), process(), and stream_out().
 { return ( m_ostr ); }
void proc_handler::stream_out (const std::string & str) protected
Definition at line 567 of file proc_ace_handler.cpp.
 {
             stream() << str;
 }
void proc_handler::stream_out (const std::string & str, unsigned long len) protected
Definition at line 580 of file proc_ace_handler.cpp.
 {
             stream() << str.substr( 0 , len );
 }
void proc_handler::stream_out (const byte_ptr & ptrBytes, unsigned long len) protected
Definition at line 572 of file proc_ace_handler.cpp.
 {
             //todo
 }
int proc_handler::svc (void) protected
Definition at line 341 of file proc_ace_handler.cpp.
 {
               ACE_Trace _( ACE_TEXT( "proc_handler::svc" ) , __LINE__ );
               char buf[BUFSIZ];
               //forever...
               while( 1 )
                 {
                   if ( this->process(buf, sizeof (buf)) == -1 )
                   {
                     return -1;
                   }
                   milliseconds dura( 50 );
                   std::this_thread::sleep_for( dura );
                 }
               return 0;
 }
proc_thread_pool_ptr proc_handler::thread_pool () protected
Definition at line 78 of file proc_ace_handler.cpp.
Referenced by handle_input().
 {           return ( acceptor()->thread_pool () ); }
std::string proc_ace::proc_handler::token () const inline noexcept
Definition at line 329 of file proc_ace_acceptor.h.
Referenced by output_no_response(), output_ok_response(), output_prompt(), and parse_command().
 { return ( m_strToken ); }
void proc_ace::proc_handler::token (const std::string & str_token) inline
Definition at line 342 of file proc_ace_acceptor.h.
 { m_strToken = str_token; }
string proc_handler::ucase (const std::string & str) static
Definition at line 843 of file proc_ace_handler.cpp.
Referenced by command_str().
 {
             string localstr( str );
             if( localstr.empty() )
             {
                 return( "" );
             }
             string::iterator iter = localstr.begin();
             while ( iter != localstr.end() )
             {
                 *iter = toupper( *iter );
                 iter++;
             }
             return ( localstr );
 }
void proc_handler::update_connection_state (proc_set_op op, proc_state state) protected
Definition at line 699 of file proc_ace_handler.cpp.
Referenced by on_login().
 {
             switch( op )
             {
                 case proc_set_op::osopAdd:
                     m_currentState.insert( state );
                     break;
                 case proc_set_op::osopDelete:
                     m_currentState.erase( state );
                     break;
                 case proc_set_op::osopClear:
                     m_currentState.clear();
                     break;
             }
 }
Member Data Documentation
ACE_thread_t proc_ace::proc_handler::creator_ protected
Definition at line 286 of file proc_ace_acceptor.h.
Referenced by handle_input().
The documentation for this class was generated from the following files:
include/proc_ace_acceptor.h
cci_daemon/src/procs/proc_ace_handler.cpp