cci daemon: proc_ace::proc_protocol_data Class Reference
proc_ace::proc_protocol_data Class Reference
#include <proc_ace_acceptor.h>
Public Member Functions
proc_protocol_data (const std::string &nametag)
virtual ~proc_protocol_data ()
std::string tag () const noexcept
std::string default_host () const noexcept
std::string dn () const noexcept
std::string document_path () const noexcept
unsigned long port () const noexcept
unsigned long thread_pool_size () const noexcept
void port (unsigned long port)
void default_host (std::string host)
void dn (std::string dn)
void document_path (std::string document_path)
void thread_pool_size (unsigned long pool_size)
Protected Attributes
std::string m_strNameTag
std::string m_strDefaultHost
std::string m_strDocumentPath
unsigned long m_dwPort
unsigned long m_dwThreads
std::string m_strDn
Detailed Description
Definition at line 123 of file proc_ace_acceptor.h.
Constructor & Destructor Documentation
proc_ace::proc_protocol_data::proc_protocol_data (const std::string & nametag) inline
Definition at line 128 of file proc_ace_acceptor.h.
                                                                        :  m_strNameTag { nametag } ,
                                                                             m_dwPort { 8000L } ,
                                                                             m_dwThreads { 125 }
                         {}
virtual proc_ace::proc_protocol_data::~proc_protocol_data () inline virtual
Definition at line 134 of file proc_ace_acceptor.h.
 {}
Member Function Documentation
std::string proc_ace::proc_protocol_data::default_host () const inline noexcept
Definition at line 149 of file proc_ace_acceptor.h.
 { return ( m_strDefaultHost ); }
void proc_ace::proc_protocol_data::default_host (std::string host) inline
Definition at line 157 of file proc_ace_acceptor.h.
 { m_strDefaultHost = host; }
std::string proc_ace::proc_protocol_data::dn () const inline noexcept
Definition at line 150 of file proc_ace_acceptor.h.
 { return ( m_strDn ); }
void proc_ace::proc_protocol_data::dn (std::string dn) inline
Definition at line 158 of file proc_ace_acceptor.h.
Referenced by dn().
 { m_strDn = dn; }
std::string proc_ace::proc_protocol_data::document_path () const inline noexcept
Definition at line 151 of file proc_ace_acceptor.h.
 { return ( m_strDocumentPath ); }
void proc_ace::proc_protocol_data::document_path (std::string document_path) inline
Definition at line 159 of file proc_ace_acceptor.h.
Referenced by document_path().
 { m_strDocumentPath = document_path; }
unsigned long proc_ace::proc_protocol_data::port () const inline noexcept
Definition at line 152 of file proc_ace_acceptor.h.
 { return ( m_dwPort ); }
void proc_ace::proc_protocol_data::port (unsigned long port) inline
Definition at line 156 of file proc_ace_acceptor.h.
Referenced by port().
 { m_dwPort = port; }
std::string proc_ace::proc_protocol_data::tag () const inline noexcept
Definition at line 148 of file proc_ace_acceptor.h.
 { return ( m_strNameTag ); }
unsigned long proc_ace::proc_protocol_data::thread_pool_size () const inline noexcept
Definition at line 153 of file proc_ace_acceptor.h.
 { return ( m_dwThreads ); }
void proc_ace::proc_protocol_data::thread_pool_size (unsigned long pool_size) inline
Definition at line 160 of file proc_ace_acceptor.h.
 { m_dwThreads = pool_size; }
Member Data Documentation
unsigned long proc_ace::proc_protocol_data::m_dwPort protected
Definition at line 141 of file proc_ace_acceptor.h.
Referenced by port().
unsigned long proc_ace::proc_protocol_data::m_dwThreads protected
Definition at line 142 of file proc_ace_acceptor.h.
Referenced by thread_pool_size().
std::string proc_ace::proc_protocol_data::m_strDefaultHost protected
Definition at line 139 of file proc_ace_acceptor.h.
Referenced by default_host().
std::string proc_ace::proc_protocol_data::m_strDn protected
Definition at line 143 of file proc_ace_acceptor.h.
Referenced by dn().
std::string proc_ace::proc_protocol_data::m_strDocumentPath protected
Definition at line 140 of file proc_ace_acceptor.h.
Referenced by document_path().
std::string proc_ace::proc_protocol_data::m_strNameTag protected
Definition at line 138 of file proc_ace_acceptor.h.
Referenced by tag().
The documentation for this class was generated from the following file:
include/proc_ace_acceptor.h