// ------------------------------
#pragma once


#include "ace/config-all.h"

#if defined (ACE_AS_STATIC_LIBS) && !defined (HAAUTH_ACE_MANAGER_HAS_DLL)
#  define HAAUTH_ACE_MANAGER_HAS_DLL 0
#endif /* ACE_AS_STATIC_LIBS && ! HAAUTH_ACE_MANAGER_HAS_DLL */

#if !defined (HAAUTH_ACE_MANAGER_HAS_DLL)
#  define HAAUTH_ACE_MANAGER_HAS_DLL 1
#endif /* ! HAAUTH_ACE_MANAGER_HAS_DLL */

#if defined (HAAUTH_ACE_MANAGER_HAS_DLL) && (HAAUTH_ACE_MANAGER_HAS_DLL == 1)
#  if defined (HAAUTH_ACE_MANAGER_BUILD_DLL)
#    define HAAUTH_ACE_MANAGER_Export ACE_Proper_Export_Flag
#    define HAAUTH_ACE_MANAGER_SINGLETON_DECLARATION(T) ACE_EXPORT_SINGLETON_DECLARATION (T)
#    define HAAUTH_ACE_MANAGER_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_EXPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  else /* HAAUTH_ACE_MANAGER_BUILD_DLL */
#    define HAAUTH_ACE_MANAGER_Export ACE_Proper_Import_Flag
#    define HAAUTH_ACE_MANAGER_SINGLETON_DECLARATION(T) ACE_IMPORT_SINGLETON_DECLARATION (T)
#    define HAAUTH_ACE_MANAGER_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_IMPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  endif /* HAAUTH_ACE_MANAGER_BUILD_DLL */
#else /* HAAUTH_ACE_MANAGER_HAS_DLL == 1 */
#  define HAAUTH_ACE_MANAGER_Export
#  define HAAUTH_ACE_MANAGER_SINGLETON_DECLARATION(T)
#  define HAAUTH_ACE_MANAGER_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#endif /* HAAUTH_ACE_MANAGER_HAS_DLL == 1 */

// Set HAAUTH_ACE_MANAGER_NTRACE = 0 to turn on library specific tracing even if
// tracing is turned off for ACE.
#if !defined (HAAUTH_ACE_MANAGER_NTRACE)
#  if (ACE_NTRACE == 1)
#    define HAAUTH_ACE_MANAGER_NTRACE 1
#  else /* (ACE_NTRACE == 1) */
#    define HAAUTH_ACE_MANAGER_NTRACE 0
#  endif /* (ACE_NTRACE == 1) */
#endif /* !HAAUTH_ACE_MANAGER_NTRACE */

#if (HAAUTH_ACE_MANAGER_NTRACE == 1)
#  define HAAUTH_ACE_MANAGER_TRACE(X)
#else /* (HAAUTH_ACE_MANAGER_NTRACE == 1) */
#  define HAAUTH_ACE_MANAGER_TRACE(X) ACE_TRACE _IMPL(X)
#endif /* (HAAUTH_ACE_MANAGER_NTRACE == 1) */


