// ------------------------------
#pragma once


#include "ace/config-all.h"

#if defined (ACE_AS_STATIC_LIBS) && !defined (HAPROCACEACCEPTOR_HAS_DLL)
#  define HAPROCACEACCEPTOR_HAS_DLL 0
#endif /* ACE_AS_STATIC_LIBS && ! HAPROCACEACCEPTOR_HAS_DLL */

#if !defined (HAPROCACEACCEPTOR_HAS_DLL)
#  define HAPROCACEACCEPTOR_HAS_DLL 1
#endif /* ! HAPROCACEACCEPTOR_HAS_DLL */

#if defined (HAPROCACEACCEPTOR_HAS_DLL) && (HAPROCACEACCEPTOR_HAS_DLL == 1)
#  if defined (HAPROCACEACCEPTOR_BUILD_DLL)
#    define HAPROCACEACCEPTOR_Export ACE_Proper_Export_Flag
#    define HAPROCACEACCEPTOR_SINGLETON_DECLARATION(T) ACE_EXPORT_SINGLETON_DECLARATION (T)
#    define HAPROCACEACCEPTOR_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_EXPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  else /* HAPROCACEACCEPTOR_BUILD_DLL */
#    define HAPROCACEACCEPTOR_Export ACE_Proper_Import_Flag
#    define HAPROCACEACCEPTOR_SINGLETON_DECLARATION(T) ACE_IMPORT_SINGLETON_DECLARATION (T)
#    define HAPROCACEACCEPTOR_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_IMPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  endif /* HAPROCACEACCEPTOR_BUILD_DLL */
#else /* HAPROCACEACCEPTOR_HAS_DLL == 1 */
#  define HAPROCACEACCEPTOR_Export
#  define HAPROCACEACCEPTOR_SINGLETON_DECLARATION(T)
#  define HAPROCACEACCEPTOR_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#endif /* HAPROCACEACCEPTOR_HAS_DLL == 1 */

// Set HAPROCACEACCEPTOR_NTRACE = 0 to turn on library specific tracing even if
// tracing is turned off for ACE.
#if !defined (HAPROCACEACCEPTOR_NTRACE)
#  if (ACE_NTRACE == 1)
#    define HAPROCACEACCEPTOR_NTRACE 1
#  else /* (ACE_NTRACE == 1) */
#    define HAPROCACEACCEPTOR_NTRACE 0
#  endif /* (ACE_NTRACE == 1) */
#endif /* !HAPROCACEACCEPTOR_NTRACE */

#if (HAPROCACEACCEPTOR_NTRACE == 1)
#  define HAPROCACEACCEPTOR_TRACE(X)
#else /* (HAPROCACEACCEPTOR_NTRACE == 1) */
#  define HAPROCACEACCEPTOR_TRACE(X) ACE_TRACE _IMPL(X)
#endif /* (HAPROCACEACCEPTOR_NTRACE == 1) */


