cci daemon: cci_daemon_impl::cci_daemon_kernel Class Reference
cci_daemon_impl::cci_daemon_kernel Class Reference
core
#include <cci_daemon_kernel.h>
Public Member Functions
cci_daemon_kernel ()
cci_daemon_kernel (std::unique_ptr< plugin_dictionary > pd)
virtual ~cci_daemon_kernel ()=default
cci_daemon_kernel (const cci_daemon_kernel &)=delete
const cci_daemon_kernel & operator= (const cci_daemon_kernel &)=delete
publish_and_subscribe_server & get_pb_server ()
virtual void load_plugin (const std::string &config)
virtual void unload_plugin (const std::string &config)
size_t plugin_count ()
virtual bool registered (const std::string &config)
Protected Member Functions
void invalidate_progeny (const std::string &config)
virtual void destroy_contexts ()
Detailed Description
core
Definition at line 39 of file cci_daemon_kernel.h.
Constructor & Destructor Documentation
cci_daemon_impl::cci_daemon_kernel::cci_daemon_kernel () inline explicit
Definition at line 47 of file cci_daemon_kernel.h.
                                                   : m_loaded_plugins( new plugin_dictionary )
                     {}
cci_daemon_impl::cci_daemon_kernel::cci_daemon_kernel (std::unique_ptr< plugin_dictionary > pd) inline explicit
Definition at line 49 of file cci_daemon_kernel.h.
                                                                                       :
                         m_loaded_plugins( std::move( pd ) )
                     {}
virtual cci_daemon_impl::cci_daemon_kernel::~cci_daemon_kernel () virtual default
cci_daemon_impl::cci_daemon_kernel::cci_daemon_kernel (const cci_daemon_kernel &) delete
Member Function Documentation
virtual void cci_daemon_impl::cci_daemon_kernel::destroy_contexts () inline protected virtual
Definition at line 86 of file cci_daemon_kernel.h.
Referenced by unload_plugin().
                     {
                          std::cerr << "...destroying plugin contexts....\n";
                          //publish and subscribe context
                          for( auto& elem : *m_loaded_plugins )
{
                                 //inform library components to clear theircontexts
                                 elem.second.clear_context( *this ) ;
                          }
                     }
publish_and_subscribe_server& cci_daemon_impl::cci_daemon_kernel::get_pb_server () inline
Definition at line 102 of file cci_daemon_kernel.h.
Referenced by ps_kafka::clear_context(), and ps_kafka::register_plugin().
 { return m_pb_server; }
void cci_daemon_impl::cci_daemon_kernel::invalidate_progeny (const std::string & config) inline protected
Definition at line 80 of file cci_daemon_kernel.h.
                     {
                         //todo
                     }
virtual void cci_daemon_impl::cci_daemon_kernel::load_plugin (const std::string & config) inline virtual
Definition at line 106 of file cci_daemon_kernel.h.
                     {
                           if( m_loaded_plugins->find( config ) == m_loaded_plugins->end() )
{
                                std::cerr << "loading plugin..."
                                          << config
                                          << "...\n";
                                cci_daemon_plugin cdp = cci_daemon_plugin( config );
                                auto iter = m_loaded_plugins->insert( std::make_pair( config , cdp ) );
                                //library instance specific , we're assigning
                                //our kernel instance for use in the library
                                //address space through function pointers
                                //--everyobdy handles their own memory management
                                //--see the constructorof the cci_dameon_plugin
                                iter.first->second.register_plugin( *this );
                                std::cerr << "...version is "
                                          << iter.first->second.get_engine_version()
                                          << "\n";
                           }
                           else
{
                              std::cerr << "...plugin already loaded...\n";
                           }
                     }
const cci_daemon_kernel& cci_daemon_impl::cci_daemon_kernel::operator= (const cci_daemon_kernel &) delete
size_t cci_daemon_impl::cci_daemon_kernel::plugin_count () inline
Definition at line 152 of file cci_daemon_kernel.h.
 { return m_loaded_plugins->size(); }
virtual bool cci_daemon_impl::cci_daemon_kernel::registered (const std::string & config) inline virtual
Definition at line 154 of file cci_daemon_kernel.h.
                     { return  m_loaded_plugins->find( config ) != m_loaded_plugins->end();   }
virtual void cci_daemon_impl::cci_daemon_kernel::unload_plugin (const std::string & config) inline virtual
Definition at line 134 of file cci_daemon_kernel.h.
                     {
                         //deregister
                         if( m_loaded_plugins->find( config ) != m_loaded_plugins->end() )
{
                             std::cerr << "...deregistering plugin..."
                                       << config
                                       << "\n";
                             std::cerr << "...releasing local contexts..\n";
                             destroy_contexts();
                             m_loaded_plugins->erase( config );
                         }
                         else
{
                              std::cerr << "...plugin not loaded...\n";
                         }
                     }
The documentation for this class was generated from the following file:
include/cci_daemon_kernel.h